name: fscl-proc
services: 
  db:
    image: postgres:17
    restart: always 
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    networks:
      - server-net
    ports:
      - 5432:5432
    volumes:
      - ../db-data:/var/lib/postgresql/data
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"
networks:
  server-net: {}